Improve the code coverage
amphp/uri pull request #14
Opened 2017-10-20 06:20 UTC by peter279k

# Changed log
- add the additional testing method.
- improve the code coverage.(see [result](https://coveralls.io/github/peter279k/uri))

2017-10-20 08:40 UTC, kelunik commented on test/UriTest.php
> +        $uri->getAuthority();
Unnecessary call.

2017-10-20 08:40 UTC, kelunik commented on test/UriTest.php
> +        $this->assertFalse($expected);
Would be good to have another test that checks with an IP.

2017-10-23 10:13 UTC, kelunik requested changes

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +    }
These should probably be two test cases, `testNormalizeEmptyUri` and `testNormalizeBasicUri` or something like that.

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +        $this->assertEquals($expected, 'www.google.com.tw:54467');
`'www.google.com.tw:54467'` is the expected value, `$uri->getAuthority()` is the actual value, so the arguments must be switched.

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +        $this->assertEquals($password, $uri->getPass());
You can just use `$this->assertEquals('password', $uri->getPass());` here, no need for an extra variable.

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +        $uri->getAuthority(true);
Useless method call.

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +        $uri = new Uri($validUri);
I guess you can just write `new Uri('ssh://...')` here instead of adding another variable.

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +        $this->assertTrue($expected);
Better use `$this->assertTrue($uri->isIpV4())` here, makes the expectation easier to read. Same applies to quite a few other places.

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +        $this->assertEquals($expected[0], 'value');
This should test for `$this->assertSame(['value'], $uri->getQueryParameterArray('parameter'));`.

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +        $uri = new Uri('http://:80');
Variable assignment can be dropped and replaced with just `new Uri(...)`.

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +        $this->assertEquals($expected, 'http://google.com.tw');
Please test something that gets otherwise normalized, such as `http://google.com:80/../test`.

2017-10-23 10:13 UTC, kelunik commented on test/UriTest.php
> +        $expected = $uri->isValid($inValidUri);
These should be static method calls, so `Uri::isValid()`.

2017-10-23 11:03 UTC, peter279k commented
Hi @kelunik, thank you for your reply.
I have modified the correct tests that you suggests.
Please review the latest commit. Thanks.

2017-10-23 11:08 UTC, kelunik requested changes
Almost good to go, just some minor changes left. :+1:

2017-10-23 11:08 UTC, kelunik commented on test/UriTest.php
> +        $this->assertFalse($uri::isValid('http://:80'));
Don't use an instance here, just call the method entirely statically: `Uri::isValid()`.

2017-10-23 11:08 UTC, kelunik commented on test/UriTest.php
> +        $this->assertEquals('password', $uri->getPass());
Please use `assertSame` over `assertEquals` where possible`.

2017-10-23 12:40 UTC, merged

2017-10-23 12:40 UTC, kelunik commented
Awesome, thanks! \o/